name: tochka_rosta
description: Skeleton Flutter app for TochkaRosta with Riverpod, go_router, Drift, and Dio.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^12.1.0
  dio: ^5.4.0
  dio_smart_retry: ^5.0.0
  drift: ^2.14.1
  drift_flutter: ^0.2.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.2
  firebase_messaging: ^14.7.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
